version: '3.8'
services:
  dust3r-demo:
    build:
      context: ./files
      dockerfile: cuda.Dockerfile 
    ports:
      - "7860:7860"
    environment:
      - DEVICE=cuda
      - MODEL=${MODEL:-DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth}
      - PYTHONPATH=/dust3r  # <--- ADD THIS LINE
    volumes:
      - ./files/checkpoints:/dust3r/checkpoints
      - ./files/data:/dust3r/data
      - ../:/dust3r
    cap_add:
      - IPC_LOCK
      - SYS_RESOURCE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
